### ISSUE TITLE
breaks if sourcefile is absolute

### ISSUE THREAD

**Issue by GuyMograbi** [linslin/grunt-jscpd-reporter#3]
if sourcefile is absolute, I get: 

`Warning: ENOENT, no such file or directory`

you can clearly see it in the code:

![image](https://cloud.githubusercontent.com/assets/287367/10508060/6eadceba-732d-11e5-9e3a-30cd57b99413.png)

**Comment by linslin** [comment]
Will be released in version 0.2.0.
